-- Per-turn token usage on agent_message so we can compute accurate cost
-- (Anthropic prices input and output differently). Only assistant rows
-- populate these; user rows leave them null.
ALTER TABLE agent_message
    ADD COLUMN prompt_tokens      INTEGER,
    ADD COLUMN completion_tokens  INTEGER;

COMMENT ON COLUMN agent_message.prompt_tokens     IS 'Input tokens sent to LLM for this turn (assistant rows only)';
COMMENT ON COLUMN agent_message.completion_tokens IS 'Output tokens generated by LLM for this turn (assistant rows only)';
