-- ============================================================
-- AUTOSALES - Automotive Dealer Sales & Reporting System
-- DB2 Database Definition Language (DDL)
-- ============================================================
-- Database: AUTODB
-- Schema:   AUTOSALES
-- Tables:   53
-- ============================================================

-- ============================================================
-- ADMIN / REFERENCE TABLES
-- ============================================================

CREATE TABLE AUTOSALE.SYSTEM_USER (
    USER_ID          CHAR(8)        NOT NULL,
    USER_NAME        VARCHAR(40)    NOT NULL,
    PASSWORD_HASH    CHAR(64)       NOT NULL,
    USER_TYPE        CHAR(1)        NOT NULL,
    -- A=Admin, M=Manager, S=Salesperson, F=F&I, C=Clerk
    DEALER_CODE      CHAR(5)        NOT NULL,
    ACTIVE_FLAG      CHAR(1)        NOT NULL DEFAULT 'Y',
    LAST_LOGIN_TS    TIMESTAMP,
    FAILED_ATTEMPTS  SMALLINT       NOT NULL DEFAULT 0,
    LOCKED_FLAG      CHAR(1)        NOT NULL DEFAULT 'N',
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE AUTOSALE.DEALER (
    DEALER_CODE      CHAR(5)        NOT NULL,
    DEALER_NAME      VARCHAR(60)    NOT NULL,
    ADDRESS_LINE1    VARCHAR(50)    NOT NULL,
    ADDRESS_LINE2    VARCHAR(50),
    CITY             VARCHAR(30)    NOT NULL,
    STATE_CODE       CHAR(2)        NOT NULL,
    ZIP_CODE         CHAR(10)       NOT NULL,
    PHONE_NUMBER     CHAR(10)       NOT NULL,
    FAX_NUMBER       CHAR(10),
    DEALER_PRINCIPAL VARCHAR(40)    NOT NULL,
    REGION_CODE      CHAR(3)        NOT NULL,
    ZONE_CODE        CHAR(2)        NOT NULL,
    OEM_DEALER_NUM   CHAR(10)       NOT NULL,
    FLOOR_PLAN_LENDER_ID  CHAR(5),
    MAX_INVENTORY    SMALLINT       NOT NULL DEFAULT 500,
    ACTIVE_FLAG      CHAR(1)        NOT NULL DEFAULT 'Y',
    OPENED_DATE      DATE           NOT NULL,
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (DEALER_CODE)
);

CREATE TABLE AUTOSALE.MODEL_MASTER (
    MODEL_YEAR       SMALLINT       NOT NULL,
    MAKE_CODE        CHAR(3)        NOT NULL,
    MODEL_CODE       CHAR(6)        NOT NULL,
    MODEL_NAME       VARCHAR(40)    NOT NULL,
    BODY_STYLE       CHAR(2)        NOT NULL,
    -- SD=Sedan, SV=SUV, TK=Truck, CP=Coupe, HB=Hatch, VN=Van, CV=Convertible
    TRIM_LEVEL       CHAR(3)        NOT NULL,
    -- BAS=Base, SPC=Sport, LTD=Limited, PLT=Platinum, GT=GT
    ENGINE_TYPE      CHAR(3)        NOT NULL,
    -- GAS=Gasoline, DSL=Diesel, HYB=Hybrid, EV=Electric
    TRANSMISSION     CHAR(1)        NOT NULL,
    -- A=Automatic, M=Manual, C=CVT
    DRIVE_TRAIN      CHAR(3)        NOT NULL,
    -- FWD=Front, RWD=Rear, AWD=All, 4WD=Four
    EXTERIOR_COLORS  VARCHAR(200),
    INTERIOR_COLORS  VARCHAR(200),
    CURB_WEIGHT      INTEGER,
    FUEL_ECONOMY_CITY   SMALLINT,
    FUEL_ECONOMY_HWY    SMALLINT,
    ACTIVE_FLAG      CHAR(1)        NOT NULL DEFAULT 'Y',
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (MODEL_YEAR, MAKE_CODE, MODEL_CODE)
);

CREATE TABLE AUTOSALE.PRICE_MASTER (
    MODEL_YEAR       SMALLINT       NOT NULL,
    MAKE_CODE        CHAR(3)        NOT NULL,
    MODEL_CODE       CHAR(6)        NOT NULL,
    MSRP             DECIMAL(11,2)  NOT NULL,
    INVOICE_PRICE    DECIMAL(11,2)  NOT NULL,
    HOLDBACK_AMT     DECIMAL(9,2)   NOT NULL DEFAULT 0,
    HOLDBACK_PCT     DECIMAL(5,3)   NOT NULL DEFAULT 0,
    DESTINATION_FEE  DECIMAL(7,2)   NOT NULL DEFAULT 0,
    ADVERTISING_FEE  DECIMAL(7,2)   NOT NULL DEFAULT 0,
    EFFECTIVE_DATE   DATE           NOT NULL,
    EXPIRY_DATE      DATE,
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (MODEL_YEAR, MAKE_CODE, MODEL_CODE, EFFECTIVE_DATE),
    FOREIGN KEY (MODEL_YEAR, MAKE_CODE, MODEL_CODE)
        REFERENCES AUTOSALE.MODEL_MASTER
);

CREATE TABLE AUTOSALE.INCENTIVE_PROGRAM (
    INCENTIVE_ID     CHAR(10)       NOT NULL,
    INCENTIVE_NAME   VARCHAR(60)    NOT NULL,
    INCENTIVE_TYPE   CHAR(2)        NOT NULL,
    -- CR=Customer Rebate, DR=Dealer Cash, LR=Loyalty, FR=Finance Rate, LB=Lease Bonus
    MODEL_YEAR       SMALLINT,
    MAKE_CODE        CHAR(3),
    MODEL_CODE       CHAR(6),
    REGION_CODE      CHAR(3),
    AMOUNT           DECIMAL(9,2)   NOT NULL DEFAULT 0,
    RATE_OVERRIDE    DECIMAL(5,3),
    START_DATE       DATE           NOT NULL,
    END_DATE         DATE           NOT NULL,
    MAX_UNITS        INTEGER,
    UNITS_USED       INTEGER        NOT NULL DEFAULT 0,
    STACKABLE_FLAG   CHAR(1)        NOT NULL DEFAULT 'N',
    ACTIVE_FLAG      CHAR(1)        NOT NULL DEFAULT 'Y',
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (INCENTIVE_ID)
);

CREATE TABLE AUTOSALE.TAX_RATE (
    STATE_CODE       CHAR(2)        NOT NULL,
    COUNTY_CODE      CHAR(5)        NOT NULL,
    CITY_CODE        CHAR(5)        NOT NULL DEFAULT '00000',
    STATE_RATE       DECIMAL(5,4)   NOT NULL,
    COUNTY_RATE      DECIMAL(5,4)   NOT NULL DEFAULT 0,
    CITY_RATE        DECIMAL(5,4)   NOT NULL DEFAULT 0,
    DOC_FEE_MAX      DECIMAL(7,2)   NOT NULL DEFAULT 0,
    TITLE_FEE        DECIMAL(7,2)   NOT NULL DEFAULT 0,
    REG_FEE          DECIMAL(7,2)   NOT NULL DEFAULT 0,
    EFFECTIVE_DATE   DATE           NOT NULL,
    EXPIRY_DATE      DATE,
    PRIMARY KEY (STATE_CODE, COUNTY_CODE, CITY_CODE, EFFECTIVE_DATE)
);

-- ============================================================
-- VEHICLE & INVENTORY TABLES
-- ============================================================

CREATE TABLE AUTOSALE.VEHICLE (
    VIN              CHAR(17)       NOT NULL,
    MODEL_YEAR       SMALLINT       NOT NULL,
    MAKE_CODE        CHAR(3)        NOT NULL,
    MODEL_CODE       CHAR(6)        NOT NULL,
    EXTERIOR_COLOR   CHAR(3)        NOT NULL,
    INTERIOR_COLOR   CHAR(3)        NOT NULL,
    ENGINE_NUM       VARCHAR(20),
    PRODUCTION_DATE  DATE,
    SHIP_DATE        DATE,
    RECEIVE_DATE     DATE,
    VEHICLE_STATUS   CHAR(2)        NOT NULL DEFAULT 'PR',
    -- PR=Produced, AL=Allocated, SH=Shipped, IT=InTransit,
    -- DL=Delivered, AV=Available, HD=Hold, SD=Sold, TR=Transfer
    DEALER_CODE      CHAR(5),
    LOT_LOCATION     CHAR(6),
    STOCK_NUMBER     CHAR(8),
    DAYS_IN_STOCK    SMALLINT       NOT NULL DEFAULT 0,
    PDI_COMPLETE     CHAR(1)        NOT NULL DEFAULT 'N',
    PDI_DATE         DATE,
    DAMAGE_FLAG      CHAR(1)        NOT NULL DEFAULT 'N',
    DAMAGE_DESC      VARCHAR(200),
    ODOMETER         INTEGER        NOT NULL DEFAULT 0,
    KEY_NUMBER       CHAR(6),
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (VIN),
    FOREIGN KEY (MODEL_YEAR, MAKE_CODE, MODEL_CODE)
        REFERENCES AUTOSALE.MODEL_MASTER
);

CREATE INDEX AUTOSALE.IX_VEH_DEALER
    ON AUTOSALE.VEHICLE (DEALER_CODE, VEHICLE_STATUS);

CREATE INDEX AUTOSALE.IX_VEH_MODEL
    ON AUTOSALE.VEHICLE (MODEL_YEAR, MAKE_CODE, MODEL_CODE);

CREATE INDEX AUTOSALE.IX_VEH_STOCK
    ON AUTOSALE.VEHICLE (STOCK_NUMBER);

CREATE TABLE AUTOSALE.VEHICLE_OPTION (
    VIN              CHAR(17)       NOT NULL,
    OPTION_CODE      CHAR(6)        NOT NULL,
    OPTION_DESC      VARCHAR(40)    NOT NULL,
    OPTION_PRICE     DECIMAL(9,2)   NOT NULL DEFAULT 0,
    INSTALLED_FLAG   CHAR(1)        NOT NULL DEFAULT 'F',
    -- F=Factory, D=Dealer, A=Aftermarket
    PRIMARY KEY (VIN, OPTION_CODE),
    FOREIGN KEY (VIN) REFERENCES AUTOSALE.VEHICLE
);

CREATE TABLE AUTOSALE.VEHICLE_STATUS_HIST (
    VIN              CHAR(17)       NOT NULL,
    STATUS_SEQ       INTEGER        NOT NULL,
    OLD_STATUS       CHAR(2)        NOT NULL,
    NEW_STATUS       CHAR(2)        NOT NULL,
    CHANGED_BY       CHAR(8)        NOT NULL,
    CHANGE_REASON    VARCHAR(60),
    CHANGED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (VIN, STATUS_SEQ),
    FOREIGN KEY (VIN) REFERENCES AUTOSALE.VEHICLE
);

CREATE TABLE AUTOSALE.LOT_LOCATION (
    DEALER_CODE      CHAR(5)        NOT NULL,
    LOCATION_CODE    CHAR(6)        NOT NULL,
    LOCATION_DESC    VARCHAR(30)    NOT NULL,
    LOCATION_TYPE    CHAR(1)        NOT NULL,
    -- S=Showroom, F=Front Lot, B=Back Lot, O=Offsite, R=Recon
    MAX_CAPACITY     SMALLINT       NOT NULL DEFAULT 0,
    CURRENT_COUNT    SMALLINT       NOT NULL DEFAULT 0,
    ACTIVE_FLAG      CHAR(1)        NOT NULL DEFAULT 'Y',
    PRIMARY KEY (DEALER_CODE, LOCATION_CODE),
    FOREIGN KEY (DEALER_CODE) REFERENCES AUTOSALE.DEALER
);

-- ============================================================
-- STOCK MANAGEMENT TABLES
-- ============================================================

CREATE TABLE AUTOSALE.STOCK_POSITION (
    DEALER_CODE      CHAR(5)        NOT NULL,
    MODEL_YEAR       SMALLINT       NOT NULL,
    MAKE_CODE        CHAR(3)        NOT NULL,
    MODEL_CODE       CHAR(6)        NOT NULL,
    ON_HAND_COUNT    SMALLINT       NOT NULL DEFAULT 0,
    IN_TRANSIT_COUNT SMALLINT       NOT NULL DEFAULT 0,
    ALLOCATED_COUNT  SMALLINT       NOT NULL DEFAULT 0,
    ON_HOLD_COUNT    SMALLINT       NOT NULL DEFAULT 0,
    SOLD_MTD         SMALLINT       NOT NULL DEFAULT 0,
    SOLD_YTD         SMALLINT       NOT NULL DEFAULT 0,
    REORDER_POINT    SMALLINT       NOT NULL DEFAULT 5,
    UPDATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (DEALER_CODE, MODEL_YEAR, MAKE_CODE, MODEL_CODE)
);

CREATE TABLE AUTOSALE.STOCK_SNAPSHOT (
    SNAPSHOT_DATE    DATE           NOT NULL,
    DEALER_CODE      CHAR(5)        NOT NULL,
    MODEL_YEAR       SMALLINT       NOT NULL,
    MAKE_CODE        CHAR(3)        NOT NULL,
    MODEL_CODE       CHAR(6)        NOT NULL,
    ON_HAND_COUNT    SMALLINT       NOT NULL DEFAULT 0,
    IN_TRANSIT_COUNT SMALLINT       NOT NULL DEFAULT 0,
    ON_HOLD_COUNT    SMALLINT       NOT NULL DEFAULT 0,
    TOTAL_VALUE      DECIMAL(13,2)  NOT NULL DEFAULT 0,
    AVG_DAYS_IN_STOCK SMALLINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (SNAPSHOT_DATE, DEALER_CODE, MODEL_YEAR, MAKE_CODE,
                 MODEL_CODE)
);

CREATE TABLE AUTOSALE.STOCK_ADJUSTMENT (
    ADJUST_ID        INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
    DEALER_CODE      CHAR(5)        NOT NULL,
    VIN              CHAR(17)       NOT NULL,
    ADJUST_TYPE      CHAR(2)        NOT NULL,
    -- DM=Damage, WO=WriteOff, RC=Reclassify, PH=Physical Count, OT=Other
    ADJUST_REASON    VARCHAR(100)   NOT NULL,
    OLD_STATUS       CHAR(2)        NOT NULL,
    NEW_STATUS       CHAR(2)        NOT NULL,
    ADJUSTED_BY      CHAR(8)        NOT NULL,
    ADJUSTED_TS      TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (ADJUST_ID)
);

CREATE TABLE AUTOSALE.STOCK_TRANSFER (
    TRANSFER_ID      INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
    FROM_DEALER      CHAR(5)        NOT NULL,
    TO_DEALER        CHAR(5)        NOT NULL,
    VIN              CHAR(17)       NOT NULL,
    TRANSFER_STATUS  CHAR(2)        NOT NULL DEFAULT 'RQ',
    -- RQ=Requested, AP=Approved, RJ=Rejected, IT=InTransit, CM=Complete
    REQUESTED_BY     CHAR(8)        NOT NULL,
    APPROVED_BY      CHAR(8),
    REQUESTED_TS     TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    APPROVED_TS      TIMESTAMP,
    COMPLETED_TS     TIMESTAMP,
    PRIMARY KEY (TRANSFER_ID)
);

-- ============================================================
-- PRODUCTION & LOGISTICS TABLES
-- ============================================================

CREATE TABLE AUTOSALE.PRODUCTION_ORDER (
    PRODUCTION_ID    CHAR(12)       NOT NULL,
    VIN              CHAR(17)       NOT NULL,
    MODEL_YEAR       SMALLINT       NOT NULL,
    MAKE_CODE        CHAR(3)        NOT NULL,
    MODEL_CODE       CHAR(6)        NOT NULL,
    PLANT_CODE       CHAR(4)        NOT NULL,
    BUILD_DATE       DATE,
    BUILD_STATUS     CHAR(2)        NOT NULL DEFAULT 'SC',
    -- SC=Scheduled, IP=InProcess, CM=Complete, QC=QualityCheck, RL=Released
    ALLOCATED_DEALER CHAR(5),
    ALLOCATION_DATE  DATE,
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (PRODUCTION_ID)
);

CREATE INDEX AUTOSALE.IX_PROD_VIN
    ON AUTOSALE.PRODUCTION_ORDER (VIN);

CREATE TABLE AUTOSALE.SHIPMENT (
    SHIPMENT_ID      CHAR(12)       NOT NULL,
    CARRIER_CODE     CHAR(5)        NOT NULL,
    CARRIER_NAME     VARCHAR(40),
    ORIGIN_PLANT     CHAR(4)        NOT NULL,
    DEST_DEALER      CHAR(5)        NOT NULL,
    TRANSPORT_MODE   CHAR(2)        NOT NULL,
    -- RL=Rail, TK=Truck, SH=Ship, ML=Multi-Leg
    VEHICLE_COUNT    SMALLINT       NOT NULL DEFAULT 0,
    SHIP_DATE        DATE,
    EST_ARRIVAL_DATE DATE,
    ACT_ARRIVAL_DATE DATE,
    SHIPMENT_STATUS  CHAR(2)        NOT NULL DEFAULT 'CR',
    -- CR=Created, DP=Dispatched, IT=InTransit, AR=Arrived, DL=Delivered
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (SHIPMENT_ID)
);

CREATE TABLE AUTOSALE.SHIPMENT_VEHICLE (
    SHIPMENT_ID      CHAR(12)       NOT NULL,
    VIN              CHAR(17)       NOT NULL,
    LOAD_SEQUENCE    SMALLINT       NOT NULL,
    PRIMARY KEY (SHIPMENT_ID, VIN),
    FOREIGN KEY (SHIPMENT_ID) REFERENCES AUTOSALE.SHIPMENT
);

CREATE TABLE AUTOSALE.TRANSIT_STATUS (
    VIN              CHAR(17)       NOT NULL,
    STATUS_SEQ       INTEGER        NOT NULL,
    LOCATION_DESC    VARCHAR(60)    NOT NULL,
    STATUS_CODE      CHAR(2)        NOT NULL,
    -- DP=Departed, AR=Arrived, TF=Transferred, DL=Delivered, DY=Delayed
    EDI_REF_NUM      CHAR(20),
    STATUS_TS        TIMESTAMP      NOT NULL,
    RECEIVED_TS      TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (VIN, STATUS_SEQ)
);

CREATE TABLE AUTOSALE.PDI_SCHEDULE (
    PDI_ID           INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
    VIN              CHAR(17)       NOT NULL,
    DEALER_CODE      CHAR(5)        NOT NULL,
    SCHEDULED_DATE   DATE           NOT NULL,
    TECHNICIAN_ID    CHAR(8),
    PDI_STATUS       CHAR(2)        NOT NULL DEFAULT 'SC',
    -- SC=Scheduled, IP=InProgress, CM=Complete, FL=Failed
    CHECKLIST_ITEMS  SMALLINT       NOT NULL DEFAULT 25,
    ITEMS_PASSED     SMALLINT       NOT NULL DEFAULT 0,
    ITEMS_FAILED     SMALLINT       NOT NULL DEFAULT 0,
    NOTES            VARCHAR(200),
    COMPLETED_TS     TIMESTAMP,
    PRIMARY KEY (PDI_ID)
);

-- ============================================================
-- CUSTOMER TABLES
-- ============================================================

CREATE TABLE AUTOSALE.CUSTOMER (
    CUSTOMER_ID      INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
    FIRST_NAME       VARCHAR(30)    NOT NULL,
    LAST_NAME        VARCHAR(30)    NOT NULL,
    MIDDLE_INIT      CHAR(1),
    DATE_OF_BIRTH    DATE,
    SSN_LAST4        CHAR(4),
    DRIVERS_LICENSE   VARCHAR(20),
    DL_STATE         CHAR(2),
    ADDRESS_LINE1    VARCHAR(50)    NOT NULL,
    ADDRESS_LINE2    VARCHAR(50),
    CITY             VARCHAR(30)    NOT NULL,
    STATE_CODE       CHAR(2)        NOT NULL,
    ZIP_CODE         CHAR(10)       NOT NULL,
    HOME_PHONE       CHAR(10),
    CELL_PHONE       CHAR(10),
    EMAIL            VARCHAR(60),
    EMPLOYER_NAME    VARCHAR(40),
    ANNUAL_INCOME    DECIMAL(11,2),
    CUSTOMER_TYPE    CHAR(1)        NOT NULL DEFAULT 'I',
    -- I=Individual, B=Business, F=Fleet
    SOURCE_CODE      CHAR(3),
    -- WLK=Walk-in, WEB=Website, REF=Referral, RPT=Repeat, ADV=Advertisement
    DEALER_CODE      CHAR(5)        NOT NULL,
    ASSIGNED_SALES   CHAR(8),
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE INDEX AUTOSALE.IX_CUST_NAME
    ON AUTOSALE.CUSTOMER (LAST_NAME, FIRST_NAME);

CREATE INDEX AUTOSALE.IX_CUST_PHONE
    ON AUTOSALE.CUSTOMER (CELL_PHONE);

CREATE INDEX AUTOSALE.IX_CUST_DLR
    ON AUTOSALE.CUSTOMER (DEALER_CODE);

CREATE TABLE AUTOSALE.CUSTOMER_LEAD (
    LEAD_ID          INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
    CUSTOMER_ID      INTEGER        NOT NULL,
    DEALER_CODE      CHAR(5)        NOT NULL,
    LEAD_SOURCE      CHAR(3)        NOT NULL,
    -- WEB=Website, PHN=Phone, WLK=Walk-in, EML=Email, EVT=Event
    INTEREST_MODEL   CHAR(6),
    INTEREST_YEAR    SMALLINT,
    LEAD_STATUS      CHAR(2)        NOT NULL DEFAULT 'NW',
    -- NW=New, CT=Contacted, AP=Appointment, TS=TestDrive, QT=Quoted,
    -- WN=Won, LS=Lost, DD=Dead
    ASSIGNED_SALES   CHAR(8)        NOT NULL,
    FOLLOW_UP_DATE   DATE,
    LAST_CONTACT_DT  DATE,
    CONTACT_COUNT    SMALLINT       NOT NULL DEFAULT 0,
    NOTES            VARCHAR(200),
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (LEAD_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES AUTOSALE.CUSTOMER
);

CREATE TABLE AUTOSALE.CREDIT_CHECK (
    CREDIT_ID        INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
    CUSTOMER_ID      INTEGER        NOT NULL,
    BUREAU_CODE      CHAR(2)        NOT NULL,
    -- EQ=Equifax, EX=Experian, TU=TransUnion
    CREDIT_SCORE     SMALLINT,
    CREDIT_TIER      CHAR(1),
    -- A=Excellent(750+), B=Good(700-749), C=Fair(650-699),
    -- D=Subprime(600-649), E=Deep(<600)
    REQUEST_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    RESPONSE_TS      TIMESTAMP,
    STATUS           CHAR(2)        NOT NULL DEFAULT 'RQ',
    -- RQ=Requested, RC=Received, ER=Error, EX=Expired
    MONTHLY_DEBT     DECIMAL(9,2),
    MONTHLY_INCOME   DECIMAL(9,2),
    DTI_RATIO        DECIMAL(5,2),
    EXPIRY_DATE      DATE,
    PRIMARY KEY (CREDIT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES AUTOSALE.CUSTOMER
);

-- ============================================================
-- SALES TABLES
-- ============================================================

CREATE TABLE AUTOSALE.SALES_DEAL (
    DEAL_NUMBER      CHAR(10)       NOT NULL,
    DEALER_CODE      CHAR(5)        NOT NULL,
    CUSTOMER_ID      INTEGER        NOT NULL,
    VIN              CHAR(17)       NOT NULL,
    SALESPERSON_ID   CHAR(8)        NOT NULL,
    SALES_MANAGER_ID CHAR(8),
    DEAL_TYPE        CHAR(1)        NOT NULL,
    -- R=Retail, L=Lease, F=Fleet, W=Wholesale
    DEAL_STATUS      CHAR(2)        NOT NULL DEFAULT 'WS',
    -- WS=Worksheet, NE=Negotiating, PA=PendingApproval, AP=Approved,
    -- FI=InF&I, CT=Contracted, DL=Delivered, CA=Cancelled, UW=Unwound
    VEHICLE_PRICE    DECIMAL(11,2)  NOT NULL DEFAULT 0,
    TOTAL_OPTIONS    DECIMAL(9,2)   NOT NULL DEFAULT 0,
    DESTINATION_FEE  DECIMAL(7,2)   NOT NULL DEFAULT 0,
    SUBTOTAL         DECIMAL(11,2)  NOT NULL DEFAULT 0,
    TRADE_ALLOW      DECIMAL(11,2)  NOT NULL DEFAULT 0,
    TRADE_PAYOFF     DECIMAL(11,2)  NOT NULL DEFAULT 0,
    NET_TRADE        DECIMAL(11,2)  NOT NULL DEFAULT 0,
    REBATES_APPLIED  DECIMAL(9,2)   NOT NULL DEFAULT 0,
    DISCOUNT_AMT     DECIMAL(9,2)   NOT NULL DEFAULT 0,
    DOC_FEE          DECIMAL(7,2)   NOT NULL DEFAULT 0,
    STATE_TAX        DECIMAL(9,2)   NOT NULL DEFAULT 0,
    COUNTY_TAX       DECIMAL(9,2)   NOT NULL DEFAULT 0,
    CITY_TAX         DECIMAL(9,2)   NOT NULL DEFAULT 0,
    TITLE_FEE        DECIMAL(7,2)   NOT NULL DEFAULT 0,
    REG_FEE          DECIMAL(7,2)   NOT NULL DEFAULT 0,
    TOTAL_PRICE      DECIMAL(11,2)  NOT NULL DEFAULT 0,
    DOWN_PAYMENT     DECIMAL(11,2)  NOT NULL DEFAULT 0,
    AMOUNT_FINANCED  DECIMAL(11,2)  NOT NULL DEFAULT 0,
    FRONT_GROSS      DECIMAL(11,2)  NOT NULL DEFAULT 0,
    BACK_GROSS       DECIMAL(11,2)  NOT NULL DEFAULT 0,
    TOTAL_GROSS      DECIMAL(11,2)  NOT NULL DEFAULT 0,
    DEAL_DATE        DATE,
    DELIVERY_DATE    DATE,
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (DEAL_NUMBER),
    FOREIGN KEY (VIN) REFERENCES AUTOSALE.VEHICLE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES AUTOSALE.CUSTOMER
);

CREATE INDEX AUTOSALE.IX_DEAL_DLR
    ON AUTOSALE.SALES_DEAL (DEALER_CODE, DEAL_DATE);

CREATE INDEX AUTOSALE.IX_DEAL_VIN
    ON AUTOSALE.SALES_DEAL (VIN);

CREATE TABLE AUTOSALE.DEAL_LINE_ITEM (
    DEAL_NUMBER      CHAR(10)       NOT NULL,
    LINE_SEQ         SMALLINT       NOT NULL,
    LINE_TYPE        CHAR(2)        NOT NULL,
    -- VH=Vehicle, OP=Option, AC=Accessory, FE=Fee, TX=Tax,
    -- RB=Rebate, DS=Discount, TR=Trade
    DESCRIPTION      VARCHAR(40)    NOT NULL,
    AMOUNT           DECIMAL(11,2)  NOT NULL,
    COST             DECIMAL(11,2)  NOT NULL DEFAULT 0,
    TAXABLE_FLAG     CHAR(1)        NOT NULL DEFAULT 'Y',
    PRIMARY KEY (DEAL_NUMBER, LINE_SEQ),
    FOREIGN KEY (DEAL_NUMBER) REFERENCES AUTOSALE.SALES_DEAL
);

CREATE TABLE AUTOSALE.TRADE_IN (
    TRADE_ID         INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
    DEAL_NUMBER      CHAR(10)       NOT NULL,
    VIN              CHAR(17),
    TRADE_YEAR       SMALLINT       NOT NULL,
    TRADE_MAKE       VARCHAR(20)    NOT NULL,
    TRADE_MODEL      VARCHAR(30)    NOT NULL,
    TRADE_COLOR      VARCHAR(15),
    ODOMETER         INTEGER        NOT NULL,
    CONDITION_CODE   CHAR(1)        NOT NULL,
    -- E=Excellent, G=Good, F=Fair, P=Poor
    ACV_AMOUNT       DECIMAL(11,2)  NOT NULL,
    ALLOWANCE_AMT    DECIMAL(11,2)  NOT NULL,
    OVER_ALLOW       DECIMAL(9,2)   NOT NULL DEFAULT 0,
    PAYOFF_AMT       DECIMAL(11,2)  NOT NULL DEFAULT 0,
    PAYOFF_BANK      VARCHAR(40),
    PAYOFF_ACCT      VARCHAR(20),
    APPRAISED_BY     CHAR(8)        NOT NULL,
    APPRAISED_TS     TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (TRADE_ID),
    FOREIGN KEY (DEAL_NUMBER) REFERENCES AUTOSALE.SALES_DEAL
);

CREATE TABLE AUTOSALE.INCENTIVE_APPLIED (
    DEAL_NUMBER      CHAR(10)       NOT NULL,
    INCENTIVE_ID     CHAR(10)       NOT NULL,
    AMOUNT_APPLIED   DECIMAL(9,2)   NOT NULL,
    APPLIED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (DEAL_NUMBER, INCENTIVE_ID),
    FOREIGN KEY (DEAL_NUMBER) REFERENCES AUTOSALE.SALES_DEAL,
    FOREIGN KEY (INCENTIVE_ID) REFERENCES AUTOSALE.INCENTIVE_PROGRAM
);

CREATE TABLE AUTOSALE.SALES_APPROVAL (
    APPROVAL_ID      INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
    DEAL_NUMBER      CHAR(10)       NOT NULL,
    APPROVAL_TYPE    CHAR(2)        NOT NULL,
    -- MG=Manager, FN=Finance, GM=General Manager
    APPROVER_ID      CHAR(8)        NOT NULL,
    APPROVAL_STATUS  CHAR(1)        NOT NULL,
    -- A=Approved, R=Rejected, P=Pending
    COMMENTS         VARCHAR(200),
    APPROVAL_TS      TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (APPROVAL_ID),
    FOREIGN KEY (DEAL_NUMBER) REFERENCES AUTOSALE.SALES_DEAL
);

-- ============================================================
-- FINANCE & INSURANCE TABLES
-- ============================================================

CREATE TABLE AUTOSALE.FINANCE_APP (
    FINANCE_ID       CHAR(12)       NOT NULL,
    DEAL_NUMBER      CHAR(10)       NOT NULL,
    CUSTOMER_ID      INTEGER        NOT NULL,
    FINANCE_TYPE     CHAR(1)        NOT NULL,
    -- L=Loan, S=Lease, C=Cash
    LENDER_CODE      CHAR(5),
    LENDER_NAME      VARCHAR(40),
    APP_STATUS       CHAR(2)        NOT NULL DEFAULT 'NW',
    -- NW=New, SB=Submitted, AP=Approved, CD=CondApproved,
    -- DN=Declined, CT=Contracted, FD=Funded
    AMOUNT_REQUESTED DECIMAL(11,2)  NOT NULL DEFAULT 0,
    AMOUNT_APPROVED  DECIMAL(11,2),
    APR_REQUESTED    DECIMAL(5,3),
    APR_APPROVED     DECIMAL(5,3),
    TERM_MONTHS      SMALLINT,
    MONTHLY_PAYMENT  DECIMAL(9,2),
    DOWN_PAYMENT     DECIMAL(11,2)  NOT NULL DEFAULT 0,
    CREDIT_TIER      CHAR(1),
    STIPULATIONS     VARCHAR(200),
    SUBMITTED_TS     TIMESTAMP,
    DECISION_TS      TIMESTAMP,
    FUNDED_TS        TIMESTAMP,
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (FINANCE_ID),
    FOREIGN KEY (DEAL_NUMBER) REFERENCES AUTOSALE.SALES_DEAL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES AUTOSALE.CUSTOMER
);

CREATE TABLE AUTOSALE.FINANCE_PRODUCT (
    DEAL_NUMBER      CHAR(10)       NOT NULL,
    PRODUCT_SEQ      SMALLINT       NOT NULL,
    PRODUCT_TYPE     CHAR(3)        NOT NULL,
    -- EXW=Extended Warranty, GAP=GAP Insurance, PPT=Paint Protection,
    -- FBR=Fabric Protection, THF=Theft Deterrent, MNT=Maintenance Plan,
    -- TIR=Tire & Wheel, DNT=Dent Protection, KEY=Key Replacement, LOJ=LoJack
    PRODUCT_NAME     VARCHAR(40)    NOT NULL,
    PROVIDER         VARCHAR(40),
    TERM_MONTHS      SMALLINT,
    MILEAGE_LIMIT    INTEGER,
    RETAIL_PRICE     DECIMAL(9,2)   NOT NULL,
    DEALER_COST      DECIMAL(9,2)   NOT NULL,
    GROSS_PROFIT     DECIMAL(9,2)   NOT NULL,
    PRIMARY KEY (DEAL_NUMBER, PRODUCT_SEQ),
    FOREIGN KEY (DEAL_NUMBER) REFERENCES AUTOSALE.SALES_DEAL
);

CREATE TABLE AUTOSALE.LEASE_TERMS (
    FINANCE_ID       CHAR(12)       NOT NULL,
    RESIDUAL_PCT     DECIMAL(5,2)   NOT NULL,
    RESIDUAL_AMT     DECIMAL(11,2)  NOT NULL,
    MONEY_FACTOR     DECIMAL(7,6)   NOT NULL,
    CAPITALIZED_COST DECIMAL(11,2)  NOT NULL,
    CAP_COST_REDUCE  DECIMAL(11,2)  NOT NULL DEFAULT 0,
    ADJ_CAP_COST     DECIMAL(11,2)  NOT NULL,
    DEPRECIATION_AMT DECIMAL(11,2)  NOT NULL,
    FINANCE_CHARGE   DECIMAL(9,2)   NOT NULL,
    MONTHLY_TAX      DECIMAL(7,2)   NOT NULL DEFAULT 0,
    MILES_PER_YEAR   INTEGER        NOT NULL DEFAULT 12000,
    EXCESS_MILE_CHG  DECIMAL(5,3)   NOT NULL DEFAULT 0.25,
    DISPOSITION_FEE  DECIMAL(7,2)   NOT NULL DEFAULT 395.00,
    ACQ_FEE          DECIMAL(7,2)   NOT NULL DEFAULT 0,
    SECURITY_DEPOSIT DECIMAL(7,2)   NOT NULL DEFAULT 0,
    PRIMARY KEY (FINANCE_ID),
    FOREIGN KEY (FINANCE_ID) REFERENCES AUTOSALE.FINANCE_APP
);

-- ============================================================
-- FLOOR PLAN FINANCING TABLES
-- ============================================================

CREATE TABLE AUTOSALE.FLOOR_PLAN_LENDER (
    LENDER_ID        CHAR(5)        NOT NULL,
    LENDER_NAME      VARCHAR(40)    NOT NULL,
    CONTACT_NAME     VARCHAR(40),
    PHONE            CHAR(10),
    BASE_RATE        DECIMAL(5,3)   NOT NULL,
    SPREAD           DECIMAL(5,3)   NOT NULL,
    CURTAILMENT_DAYS INTEGER        NOT NULL DEFAULT 90,
    FREE_FLOOR_DAYS  INTEGER        NOT NULL DEFAULT 0,
    PRIMARY KEY (LENDER_ID)
);

CREATE TABLE AUTOSALE.FLOOR_PLAN_VEHICLE (
    FLOOR_PLAN_ID    INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
    VIN              CHAR(17)       NOT NULL,
    DEALER_CODE      CHAR(5)        NOT NULL,
    LENDER_ID        CHAR(5)        NOT NULL,
    INVOICE_AMOUNT   DECIMAL(11,2)  NOT NULL,
    CURRENT_BALANCE  DECIMAL(11,2)  NOT NULL,
    INTEREST_ACCRUED DECIMAL(9,2)   NOT NULL DEFAULT 0,
    FLOOR_DATE       DATE           NOT NULL,
    CURTAILMENT_DATE DATE,
    PAYOFF_DATE      DATE,
    FP_STATUS        CHAR(2)        NOT NULL DEFAULT 'AC',
    -- AC=Active, CT=Curtailed, PD=PaidOff, WO=WriteOff
    DAYS_ON_FLOOR    SMALLINT       NOT NULL DEFAULT 0,
    LAST_INTEREST_DT DATE,
    PRIMARY KEY (FLOOR_PLAN_ID),
    FOREIGN KEY (VIN) REFERENCES AUTOSALE.VEHICLE,
    FOREIGN KEY (LENDER_ID) REFERENCES AUTOSALE.FLOOR_PLAN_LENDER
);

CREATE INDEX AUTOSALE.IX_FP_VIN
    ON AUTOSALE.FLOOR_PLAN_VEHICLE (VIN);

CREATE INDEX AUTOSALE.IX_FP_DEALER
    ON AUTOSALE.FLOOR_PLAN_VEHICLE (DEALER_CODE, FP_STATUS);

CREATE TABLE AUTOSALE.FLOOR_PLAN_INTEREST (
    INTEREST_ID      INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
    FLOOR_PLAN_ID    INTEGER        NOT NULL,
    CALC_DATE        DATE           NOT NULL,
    PRINCIPAL_BAL    DECIMAL(11,2)  NOT NULL,
    RATE_APPLIED     DECIMAL(5,3)   NOT NULL,
    DAILY_INTEREST   DECIMAL(9,4)   NOT NULL,
    CUMULATIVE_INT   DECIMAL(9,2)   NOT NULL,
    PRIMARY KEY (INTEREST_ID),
    FOREIGN KEY (FLOOR_PLAN_ID) REFERENCES AUTOSALE.FLOOR_PLAN_VEHICLE
);

-- ============================================================
-- WARRANTY & RECALL TABLES
-- ============================================================

CREATE TABLE AUTOSALE.WARRANTY (
    WARRANTY_ID      INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
    VIN              CHAR(17)       NOT NULL,
    DEAL_NUMBER      CHAR(10)       NOT NULL,
    WARRANTY_TYPE    CHAR(2)        NOT NULL,
    -- BT=Basic/Bumper-to-Bumper, PT=Powertrain, CR=Corrosion, EM=Emission
    START_DATE       DATE           NOT NULL,
    EXPIRY_DATE      DATE           NOT NULL,
    MILEAGE_LIMIT    INTEGER        NOT NULL,
    DEDUCTIBLE       DECIMAL(7,2)   NOT NULL DEFAULT 0,
    ACTIVE_FLAG      CHAR(1)        NOT NULL DEFAULT 'Y',
    REGISTERED_TS    TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (WARRANTY_ID),
    FOREIGN KEY (VIN) REFERENCES AUTOSALE.VEHICLE
);

CREATE TABLE AUTOSALE.RECALL_CAMPAIGN (
    RECALL_ID        CHAR(10)       NOT NULL,
    NHTSA_NUM        CHAR(12),
    RECALL_DESC      VARCHAR(200)   NOT NULL,
    SEVERITY         CHAR(1)        NOT NULL,
    -- C=Critical, H=High, M=Medium, L=Low
    AFFECTED_YEARS   VARCHAR(40)    NOT NULL,
    AFFECTED_MODELS  VARCHAR(100)   NOT NULL,
    REMEDY_DESC      VARCHAR(200)   NOT NULL,
    REMEDY_AVAIL_DT  DATE,
    ANNOUNCED_DATE   DATE           NOT NULL,
    TOTAL_AFFECTED   INTEGER        NOT NULL DEFAULT 0,
    TOTAL_COMPLETED  INTEGER        NOT NULL DEFAULT 0,
    CAMPAIGN_STATUS  CHAR(1)        NOT NULL DEFAULT 'A',
    -- A=Active, C=Complete, P=Pending Parts
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (RECALL_ID)
);

CREATE TABLE AUTOSALE.RECALL_VEHICLE (
    RECALL_ID        CHAR(10)       NOT NULL,
    VIN              CHAR(17)       NOT NULL,
    DEALER_CODE      CHAR(5),
    RECALL_STATUS    CHAR(2)        NOT NULL DEFAULT 'OP',
    -- OP=Open, SC=Scheduled, IP=InProgress, CM=Complete, NA=NotApplicable
    NOTIFIED_DATE    DATE,
    SCHEDULED_DATE   DATE,
    COMPLETED_DATE   DATE,
    TECHNICIAN_ID    CHAR(8),
    PARTS_ORDERED    CHAR(1)        NOT NULL DEFAULT 'N',
    PARTS_AVAIL      CHAR(1)        NOT NULL DEFAULT 'N',
    PRIMARY KEY (RECALL_ID, VIN),
    FOREIGN KEY (RECALL_ID) REFERENCES AUTOSALE.RECALL_CAMPAIGN
);

CREATE TABLE AUTOSALE.RECALL_NOTIFICATION (
    NOTIF_ID         INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
    RECALL_ID        CHAR(10)       NOT NULL,
    VIN              CHAR(17)       NOT NULL,
    CUSTOMER_ID      INTEGER,
    NOTIF_TYPE       CHAR(1)        NOT NULL,
    -- M=Mail, E=Email, P=Phone, S=SMS
    NOTIF_DATE       DATE           NOT NULL,
    RESPONSE_FLAG    CHAR(1)        NOT NULL DEFAULT 'N',
    PRIMARY KEY (NOTIF_ID),
    FOREIGN KEY (RECALL_ID) REFERENCES AUTOSALE.RECALL_CAMPAIGN
);

-- ============================================================
-- REGISTRATION & TITLE TABLES
-- ============================================================

CREATE TABLE AUTOSALE.REGISTRATION (
    REG_ID           CHAR(12)       NOT NULL,
    DEAL_NUMBER      CHAR(10)       NOT NULL,
    VIN              CHAR(17)       NOT NULL,
    CUSTOMER_ID      INTEGER        NOT NULL,
    REG_STATE        CHAR(2)        NOT NULL,
    REG_TYPE         CHAR(2)        NOT NULL,
    -- NW=New, TF=Transfer, RN=Renewal, DP=Duplicate
    PLATE_NUMBER     VARCHAR(10),
    TITLE_NUMBER     VARCHAR(20),
    LIEN_HOLDER      VARCHAR(60),
    LIEN_HOLDER_ADDR VARCHAR(100),
    REG_STATUS       CHAR(2)        NOT NULL DEFAULT 'PR',
    -- PR=Preparing, VL=Validated, SB=Submitted, PG=Processing,
    -- IS=Issued, RJ=Rejected, ER=Error
    SUBMISSION_DATE  DATE,
    ISSUED_DATE      DATE,
    REG_FEE_PAID     DECIMAL(7,2)   NOT NULL DEFAULT 0,
    TITLE_FEE_PAID   DECIMAL(7,2)   NOT NULL DEFAULT 0,
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (REG_ID),
    FOREIGN KEY (DEAL_NUMBER) REFERENCES AUTOSALE.SALES_DEAL,
    FOREIGN KEY (VIN) REFERENCES AUTOSALE.VEHICLE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES AUTOSALE.CUSTOMER
);

CREATE TABLE AUTOSALE.TITLE_STATUS (
    REG_ID           CHAR(12)       NOT NULL,
    STATUS_SEQ       SMALLINT       NOT NULL,
    STATUS_CODE      CHAR(2)        NOT NULL,
    STATUS_DESC      VARCHAR(60),
    STATUS_TS        TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (REG_ID, STATUS_SEQ),
    FOREIGN KEY (REG_ID) REFERENCES AUTOSALE.REGISTRATION
);

-- ============================================================
-- REPORTING TABLES
-- ============================================================

CREATE TABLE AUTOSALE.DAILY_SALES_SUMMARY (
    SUMMARY_DATE     DATE           NOT NULL,
    DEALER_CODE      CHAR(5)        NOT NULL,
    MODEL_YEAR       SMALLINT       NOT NULL,
    MAKE_CODE        CHAR(3)        NOT NULL,
    MODEL_CODE       CHAR(6)        NOT NULL,
    UNITS_SOLD       SMALLINT       NOT NULL DEFAULT 0,
    TOTAL_REVENUE    DECIMAL(13,2)  NOT NULL DEFAULT 0,
    TOTAL_GROSS      DECIMAL(11,2)  NOT NULL DEFAULT 0,
    FRONT_GROSS      DECIMAL(11,2)  NOT NULL DEFAULT 0,
    BACK_GROSS       DECIMAL(11,2)  NOT NULL DEFAULT 0,
    AVG_SELLING_PRICE DECIMAL(11,2) NOT NULL DEFAULT 0,
    AVG_GROSS_PER_UNIT DECIMAL(9,2) NOT NULL DEFAULT 0,
    PRIMARY KEY (SUMMARY_DATE, DEALER_CODE, MODEL_YEAR, MAKE_CODE,
                 MODEL_CODE)
);

CREATE TABLE AUTOSALE.MONTHLY_SNAPSHOT (
    SNAPSHOT_MONTH   CHAR(6)        NOT NULL,
    -- Format: YYYYMM
    DEALER_CODE      CHAR(5)        NOT NULL,
    TOTAL_UNITS_SOLD SMALLINT       NOT NULL DEFAULT 0,
    TOTAL_REVENUE    DECIMAL(15,2)  NOT NULL DEFAULT 0,
    TOTAL_GROSS      DECIMAL(13,2)  NOT NULL DEFAULT 0,
    TOTAL_FI_GROSS   DECIMAL(11,2)  NOT NULL DEFAULT 0,
    AVG_DAYS_TO_SELL SMALLINT       NOT NULL DEFAULT 0,
    INVENTORY_TURN   DECIMAL(5,2)   NOT NULL DEFAULT 0,
    FI_PER_DEAL      DECIMAL(9,2)   NOT NULL DEFAULT 0,
    CSI_SCORE        DECIMAL(5,2),
    FROZEN_FLAG      CHAR(1)        NOT NULL DEFAULT 'N',
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (SNAPSHOT_MONTH, DEALER_CODE)
);

CREATE TABLE AUTOSALE.COMMISSION (
    COMMISSION_ID    INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
    DEALER_CODE      CHAR(5)        NOT NULL,
    SALESPERSON_ID   CHAR(8)        NOT NULL,
    DEAL_NUMBER      CHAR(10)       NOT NULL,
    COMM_TYPE        CHAR(2)        NOT NULL,
    -- FR=Front Gross, BK=Back Gross, BN=Bonus, SP=Spiff, MN=Mini
    GROSS_AMOUNT     DECIMAL(11,2)  NOT NULL,
    COMM_RATE        DECIMAL(5,4)   NOT NULL,
    COMM_AMOUNT      DECIMAL(9,2)   NOT NULL,
    PAY_PERIOD       CHAR(6)        NOT NULL,
    -- Format: YYYYMM
    PAID_FLAG        CHAR(1)        NOT NULL DEFAULT 'N',
    CALC_TS          TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (COMMISSION_ID),
    FOREIGN KEY (DEAL_NUMBER) REFERENCES AUTOSALE.SALES_DEAL
);

-- ============================================================
-- BATCH CONTROL TABLES
-- ============================================================

CREATE TABLE AUTOSALE.RESTART_CONTROL (
    JOB_NAME         CHAR(8)        NOT NULL,
    STEP_NAME        CHAR(8)        NOT NULL,
    CHECKPOINT_ID    CHAR(20)       NOT NULL,
    RECORDS_PROCESSED INTEGER       NOT NULL DEFAULT 0,
    LAST_KEY_VALUE   VARCHAR(50),
    RESTART_FLAG     CHAR(1)        NOT NULL DEFAULT 'N',
    STATUS           CHAR(1)        NOT NULL DEFAULT 'C',
    -- C=Complete, A=Active, F=Failed, R=Restarting
    STARTED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    CHECKPOINT_TS    TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    COMPLETED_TS     TIMESTAMP,
    PRIMARY KEY (JOB_NAME, STEP_NAME)
);

CREATE TABLE AUTOSALE.AUDIT_LOG (
    AUDIT_ID         INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
    USER_ID          CHAR(8)        NOT NULL,
    PROGRAM_ID       CHAR(8)        NOT NULL,
    ACTION_TYPE      CHAR(3)        NOT NULL,
    -- INS=Insert, UPD=Update, DEL=Delete, INQ=Inquiry, LOG=Login,
    -- APV=Approval, RJT=Reject, PRT=Print
    TABLE_NAME       VARCHAR(30),
    KEY_VALUE        VARCHAR(50),
    OLD_VALUE        VARCHAR(200),
    NEW_VALUE        VARCHAR(200),
    AUDIT_TS         TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (AUDIT_ID)
);

CREATE INDEX AUTOSALE.IX_AUDIT_USER
    ON AUTOSALE.AUDIT_LOG (USER_ID, AUDIT_TS);

CREATE INDEX AUTOSALE.IX_AUDIT_PGM
    ON AUTOSALE.AUDIT_LOG (PROGRAM_ID, AUDIT_TS);

-- ============================================================
-- SYSTEM CONFIGURATION TABLE
-- ============================================================

CREATE TABLE AUTOSALE.SYSTEM_CONFIG (
    CONFIG_KEY       VARCHAR(30)    NOT NULL,
    CONFIG_VALUE     VARCHAR(100)   NOT NULL,
    CONFIG_DESC      VARCHAR(60),
    UPDATED_BY       CHAR(8),
    UPDATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (CONFIG_KEY)
);

-- ============================================================
-- SALESPERSON TABLE
-- ============================================================

CREATE TABLE AUTOSALE.SALESPERSON (
    SALESPERSON_ID   CHAR(8)        NOT NULL,
    SALESPERSON_NAME VARCHAR(30)    NOT NULL,
    DEALER_CODE      CHAR(5)        NOT NULL,
    HIRE_DATE        DATE,
    TERMINATION_DATE DATE,
    COMMISSION_PLAN  CHAR(2)        NOT NULL DEFAULT 'ST',
    -- ST=Standard, SR=Senior, MG=Manager, TR=Trainee
    ACTIVE_FLAG      CHAR(1)        NOT NULL DEFAULT 'Y',
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (SALESPERSON_ID),
    FOREIGN KEY (DEALER_CODE) REFERENCES AUTOSALE.DEALER
);

CREATE INDEX AUTOSALE.IX_SP_DEALER
    ON AUTOSALE.SALESPERSON (DEALER_CODE, ACTIVE_FLAG);

-- ============================================================
-- LENDER TABLE
-- ============================================================

CREATE TABLE AUTOSALE.LENDER (
    LENDER_ID        CHAR(5)        NOT NULL,
    LENDER_NAME      VARCHAR(40)    NOT NULL,
    CONTACT_NAME     VARCHAR(40),
    PHONE            CHAR(10),
    ADDRESS_LINE1    VARCHAR(50),
    CITY             VARCHAR(30),
    STATE_CODE       CHAR(2),
    ZIP_CODE         CHAR(10),
    LENDER_TYPE      CHAR(2)        NOT NULL DEFAULT 'FP',
    -- FP=Floor Plan, RT=Retail, LS=Lease, AL=All
    BASE_RATE        DECIMAL(5,3)   NOT NULL DEFAULT 0,
    SPREAD           DECIMAL(5,3)   NOT NULL DEFAULT 0,
    CURTAILMENT_DAYS INTEGER        NOT NULL DEFAULT 90,
    FREE_FLOOR_DAYS  INTEGER        NOT NULL DEFAULT 0,
    ACTIVE_FLAG      CHAR(1)        NOT NULL DEFAULT 'Y',
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (LENDER_ID)
);

-- ============================================================
-- PRICE SCHEDULE TABLE
-- ============================================================

CREATE TABLE AUTOSALE.PRICE_SCHEDULE (
    MODEL_YEAR       SMALLINT       NOT NULL,
    MAKE_CODE        CHAR(3)        NOT NULL,
    MODEL_CODE       CHAR(6)        NOT NULL,
    SCHEDULE_TYPE    CHAR(2)        NOT NULL,
    -- MS=MSRP, IN=Invoice, DL=Dealer, FL=Fleet
    MSRP             DECIMAL(11,2)  NOT NULL DEFAULT 0,
    INVOICE_PRICE    DECIMAL(11,2)  NOT NULL DEFAULT 0,
    DEALER_PRICE     DECIMAL(11,2)  NOT NULL DEFAULT 0,
    HOLDBACK_AMT     DECIMAL(9,2)   NOT NULL DEFAULT 0,
    DESTINATION_FEE  DECIMAL(7,2)   NOT NULL DEFAULT 0,
    EFFECTIVE_DATE   DATE           NOT NULL,
    EXPIRY_DATE      DATE,
    ACTIVE_FLAG      CHAR(1)        NOT NULL DEFAULT 'Y',
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (MODEL_YEAR, MAKE_CODE, MODEL_CODE, SCHEDULE_TYPE,
                 EFFECTIVE_DATE),
    FOREIGN KEY (MODEL_YEAR, MAKE_CODE, MODEL_CODE)
        REFERENCES AUTOSALE.MODEL_MASTER
);

-- ============================================================
-- F&I DEAL PRODUCT TABLE
-- ============================================================

CREATE TABLE AUTOSALE.FI_DEAL_PRODUCT (
    DEAL_NUMBER      CHAR(10)       NOT NULL,
    PRODUCT_SEQ      SMALLINT       NOT NULL,
    PRODUCT_TYPE     CHAR(3)        NOT NULL,
    -- EXW=Extended Warranty, GAP=GAP Insurance, PPT=Paint Protection,
    -- FBR=Fabric Protection, THF=Theft Deterrent, MNT=Maintenance Plan,
    -- TIR=Tire & Wheel, DNT=Dent Protection, KEY=Key Replacement, LOJ=LoJack
    PRODUCT_NAME     VARCHAR(40)    NOT NULL,
    PROVIDER         VARCHAR(40),
    TERM_MONTHS      SMALLINT,
    MILEAGE_LIMIT    INTEGER,
    SELLING_PRICE    DECIMAL(9,2)   NOT NULL,
    DEALER_COST      DECIMAL(9,2)   NOT NULL,
    GROSS_PROFIT     DECIMAL(9,2)   NOT NULL,
    PRIMARY KEY (DEAL_NUMBER, PRODUCT_SEQ),
    FOREIGN KEY (DEAL_NUMBER) REFERENCES AUTOSALE.SALES_DEAL
);

-- ============================================================
-- COMMISSION AUDIT TABLE
-- ============================================================

CREATE TABLE AUTOSALE.COMMISSION_AUDIT (
    AUDIT_ID         INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
    DEAL_NUMBER      CHAR(10)       NOT NULL,
    ENTITY_TYPE      CHAR(8)        NOT NULL,
    -- WARR_REG=Warranty Registration, VEH_REG=Vehicle Registration,
    -- COMM_CAL=Commission Calculated, COMM_ADJ=Commission Adjusted
    DESCRIPTION      VARCHAR(200)   NOT NULL,
    AUDIT_TS         TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (AUDIT_ID),
    FOREIGN KEY (DEAL_NUMBER) REFERENCES AUTOSALE.SALES_DEAL
);

CREATE INDEX AUTOSALE.IX_COMM_AUDIT_DEAL
    ON AUTOSALE.COMMISSION_AUDIT (DEAL_NUMBER);

-- ============================================================
-- WARRANTY CLAIM TABLE
-- ============================================================

CREATE TABLE AUTOSALE.WARRANTY_CLAIM (
    CLAIM_NUMBER     CHAR(8)        NOT NULL,
    VIN              CHAR(17)       NOT NULL,
    DEALER_CODE      CHAR(5)        NOT NULL,
    CLAIM_TYPE       CHAR(2)        NOT NULL,
    -- BA=Basic, PT=Powertrain, EX=Extended, GW=Goodwill,
    -- RC=Recall, CM=Campaign, PD=Pre-Delivery
    CLAIM_DATE       DATE           NOT NULL,
    REPAIR_DATE      DATE,
    LABOR_AMT        DECIMAL(9,2)   NOT NULL DEFAULT 0,
    PARTS_AMT        DECIMAL(9,2)   NOT NULL DEFAULT 0,
    TOTAL_CLAIM      DECIMAL(9,2)   NOT NULL DEFAULT 0,
    CLAIM_STATUS     CHAR(2)        NOT NULL DEFAULT 'NW',
    -- NW=New, SB=Submitted, AP=Approved, PA=Partial Approved,
    -- PD=Paid, DN=Denied, CL=Closed
    TECHNICIAN_ID    CHAR(8),
    REPAIR_ORDER_NUM VARCHAR(12),
    NOTES            VARCHAR(200),
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (CLAIM_NUMBER),
    FOREIGN KEY (VIN) REFERENCES AUTOSALE.VEHICLE
);

CREATE INDEX AUTOSALE.IX_WC_DEALER
    ON AUTOSALE.WARRANTY_CLAIM (DEALER_CODE, CLAIM_STATUS);

CREATE INDEX AUTOSALE.IX_WC_VIN
    ON AUTOSALE.WARRANTY_CLAIM (VIN);

CREATE INDEX AUTOSALE.IX_WC_DATE
    ON AUTOSALE.WARRANTY_CLAIM (CLAIM_DATE);

-- ============================================================
-- BATCH CONTROL TABLE
-- ============================================================

CREATE TABLE AUTOSALE.BATCH_CONTROL (
    PROGRAM_ID       CHAR(8)        NOT NULL,
    LAST_RUN_DATE    DATE,
    LAST_SYNC_DATE   DATE,
    RECORDS_PROCESSED INTEGER       NOT NULL DEFAULT 0,
    RUN_STATUS       CHAR(2)        NOT NULL DEFAULT 'CP',
    -- CP=Complete, IP=In Progress, FL=Failed, SK=Skipped
    CREATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    UPDATED_TS       TIMESTAMP      NOT NULL DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (PROGRAM_ID)
);

-- ============================================================
-- BATCH CHECKPOINT TABLE
-- ============================================================

CREATE TABLE AUTOSALE.BATCH_CHECKPOINT (
    PROGRAM_ID       CHAR(8)        NOT NULL,
    CHECKPOINT_SEQ   INTEGER        NOT NULL,
    CHECKPOINT_TIMESTAMP TIMESTAMP  NOT NULL DEFAULT CURRENT TIMESTAMP,
    LAST_KEY_VALUE   VARCHAR(30),
    RECORDS_IN       INTEGER        NOT NULL DEFAULT 0,
    RECORDS_OUT      INTEGER        NOT NULL DEFAULT 0,
    RECORDS_ERROR    INTEGER        NOT NULL DEFAULT 0,
    CHECKPOINT_STATUS CHAR(2)       NOT NULL DEFAULT 'AC',
    -- AC=Active, CP=Complete, FL=Failed, RS=Restarted
    PRIMARY KEY (PROGRAM_ID, CHECKPOINT_SEQ)
);

-- ============================================================
-- SEQUENCES
-- ============================================================

CREATE SEQUENCE AUTOSALE.FPL_SEQ
    AS INTEGER
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE
    CACHE 20;

CREATE SEQUENCE AUTOSALE.REG_SEQ
    AS INTEGER
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE
    CACHE 20;

CREATE SEQUENCE AUTOSALE.REG_TRACK_SEQ
    AS INTEGER
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE
    CACHE 20;

CREATE SEQUENCE AUTOSALE.WARR_SEQ
    AS INTEGER
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE
    CACHE 20;

-- ============================================================
-- GRANTS
-- ============================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.SYSTEM_USER        TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.DEALER             TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.MODEL_MASTER       TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.PRICE_MASTER       TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.INCENTIVE_PROGRAM  TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.TAX_RATE           TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.VEHICLE            TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.VEHICLE_OPTION     TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.VEHICLE_STATUS_HIST TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.LOT_LOCATION       TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.STOCK_POSITION     TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.STOCK_SNAPSHOT     TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.STOCK_ADJUSTMENT   TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.STOCK_TRANSFER     TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.PRODUCTION_ORDER   TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.SHIPMENT           TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.SHIPMENT_VEHICLE   TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.TRANSIT_STATUS     TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.PDI_SCHEDULE       TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.CUSTOMER           TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.CUSTOMER_LEAD      TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.CREDIT_CHECK       TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.SALES_DEAL         TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.DEAL_LINE_ITEM     TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.TRADE_IN           TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.INCENTIVE_APPLIED  TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.SALES_APPROVAL     TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.FINANCE_APP        TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.FINANCE_PRODUCT    TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.LEASE_TERMS        TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.FLOOR_PLAN_LENDER  TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.FLOOR_PLAN_VEHICLE TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.FLOOR_PLAN_INTEREST TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.WARRANTY           TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.RECALL_CAMPAIGN    TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.RECALL_VEHICLE     TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.RECALL_NOTIFICATION TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.REGISTRATION       TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.TITLE_STATUS       TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.DAILY_SALES_SUMMARY TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.MONTHLY_SNAPSHOT   TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.COMMISSION         TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.RESTART_CONTROL    TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.AUDIT_LOG          TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.SYSTEM_CONFIG      TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.SALESPERSON        TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.LENDER             TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.PRICE_SCHEDULE     TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.FI_DEAL_PRODUCT    TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.COMMISSION_AUDIT   TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.WARRANTY_CLAIM     TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.BATCH_CONTROL      TO ROLE AUTOSALES_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON AUTOSALE.BATCH_CHECKPOINT   TO ROLE AUTOSALES_APP;
GRANT USAGE ON SEQUENCE AUTOSALE.FPL_SEQ        TO ROLE AUTOSALES_APP;
GRANT USAGE ON SEQUENCE AUTOSALE.REG_SEQ        TO ROLE AUTOSALES_APP;
GRANT USAGE ON SEQUENCE AUTOSALE.REG_TRACK_SEQ  TO ROLE AUTOSALES_APP;
GRANT USAGE ON SEQUENCE AUTOSALE.WARR_SEQ       TO ROLE AUTOSALES_APP;

-- ============================================================
-- END OF DDL
-- ============================================================
